# Generated by Django 3.1 on 2020-08-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bid_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='price',
        ),
        migrations.AddField(
            model_name='auction',
            name='photo',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.RemoveField(
            model_name='auction',
            name='bids',
        ),
        migrations.AddField(
            model_name='auction',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='auctions', to='auctions.Bid'),
        ),
        migrations.RemoveField(
            model_name='auction',
            name='comments',
        ),
        migrations.AddField(
            model_name='auction',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='auctions', to='auctions.Comment'),
        ),
    ]
