# Generated by Django 3.1 on 2020-08-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='isClosed',
            field=models.CharField(default='FALSE', max_length=10),
        ),
    ]
