# Generated by Django 3.1 on 2020-08-26 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_isclosed'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='watchlisted',
            field=models.ManyToManyField(blank=True, related_name='watchlisted', to=settings.AUTH_USER_MODEL),
        ),
    ]
